FROM quay.io/almalinuxorg/8-base:8

ENV RUSTUP_HOME=/opt/rustup \
    CARGO_HOME=/opt/cargo \
    PATH=/opt/cargo/bin:${PATH}

RUN dnf -y update && \
    dnf -y install rsync gcc && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
      sh -s -- -y \
        --default-toolchain stable \
        --no-modify-path

WORKDIR /work
